version: "3"
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    container_name: "docker-mongodb"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root